### ISSUE TITLE
Question about the figure

### ISSUE THREAD

**Issue by Vanint** [17Skye17/VideoLT#2]
Thanks for your great work and contribution. I have one question: how can I draw a picture like Figure 2 (the taxonomy structure of VideoLT) in your paper? Do you use MATLAB or other softwares?

**Comment by 17Skye17** [comment]
Hi, thank you for your interest in our work.
We use Echarts to draw this picture: [https://echarts.apache.org/examples/en/index.html](https://echarts.apache.org/examples/en/index.html)

**Comment by 17Skye17** [comment]
Feel free to reopen this issue if you have any questions.

**Comment by YifanZhang07** [comment]
Thanks for your reply. 

BTW, we recently released **the first comprehensive survey for deep long-tailed learning** (https://arxiv.org/pdf/2110.04596.pdf) to the community. In this survey, we review your proposed method and Video-LT dataset, and also highlight the long-tailed video learning as an important direction for future research. We hope such a direction can attract increasing attention. Thanks again for your contribution to the community. 

If you are interested, please refer to our survey. Cheers.

**Comment by 17Skye17** [comment]
Hi, thank you for your positive comments. We are happy to read this survey, it provides us a thorough discussion of recent long-tailed recognition literature , we believe it would benefit the community a lot. : )

**Comment by 17Skye17** [comment]
> Thanks for your reply.
> 
> BTW, we recently released **the first comprehensive survey for deep long-tailed learning** (https://arxiv.org/pdf/2110.04596.pdf) to the community. In this survey, we review your proposed method and Video-LT dataset, and also highlight the long-tailed video learning as an important direction for future research. We hope such a direction can attract increasing attention. Thanks again for your contribution to the community.
> 
> If you are interested, please refer to our survey. Cheers.

Hi, thank you for your positive comments. We are happy to read this survey, it provides us a thorough discussion of recent long-tailed recognition literature, we believe it would benefit the community a lot. : )
