### ISSUE TITLE
关于下载数据集annotion的问题

### ISSUE THREAD

**Issue by laohuijiadezhu** [17Skye17/VideoLT#3]
在这个网站上 https://videolt.github.io/ 无法下载annotion，点击后是空白页

**Comment by 17Skye17** [comment]
您好，

由于数据license的问题我们的网站目前不提供数据的下载直链，需要数据集可以发送邮件到zhangxing18@fudan.edu.cn。

PS. 您可以clone这个repo，其中的labels文件夹包含了annotation。

祝好！
